export const CHANGE_INVENTORY = 'change-inventory';

export const STORE_STORES = [
  'ALDO Centre Eaton',
  'ALDO Destiny USA Mall',
  'ALDO Pheasant Lane Mall',
  'ALDO Holyoke Mall',
  'ALDO Maine Mall',
  'ALDO Crossgates Mall',
  'ALDO Burlington Mall',
  'ALDO Solomon Pond Mall',
  'ALDO Auburn Mall',
  'ALDO Waterloo Premium Outlets',
];
export const SHOES_MODELS = [
  'ADERI',
  'MIRIRA',
  'CAELAN',
  'BUTAUD',
  'SCHOOLER',
  'SODANO',
  'MCTYRE',
  'CADAUDIA',
  'RASIEN',
  'WUMA',
  'GRELIDIEN',
  'CADEVEN',
  'SEVIDE',
  'ELOILLAN',
  'BEODA',
  'VENDOGNUS',
  'ABOEN',
  'ALALIWEN',
  'GREG',
  'BOZZA',
];
